url: https://islp-bolivia.github.io
baseurl: ""
# Site settings
title: Alfabetización Estadística Bolivia 
email: mailto:islp.bolivia@gmail.com
description: "Competencia Boliviana de Posters Estadísticos — Quinta versión 2026-2027. Inscripciones abiertas!"


# Team names, titles and social links
people:

- name: Fundación ARU
  pic: arulogo
  position: Instituto de Investigación
  social:
    - title: twitter
      url: https://twitter.com/arufoundation?lang=es
    - title: facebook
      url: https://www.facebook.com/FundacionARU
    - title: dribbble
      url: https://www.aru.org.bo/
- name: Carrera de Estadística
  pic: stat
  position: Casa de Estudio Superior
  social:
    - title: facebook
      url: https://www.facebook.com/estadisticaumsa
    - title: dribbble
      url: https://estadistica.umsa.bo/	
#- name: Instituto Nacional de Estadística
#  pic: ine
#  position: Estado Plurinacional de Bolivia
#  social:
#    - title: twitter
#      url: https://twitter.com/ineoficialbo?lang=es
#    - title: facebook
#      url: https://www.facebook.com/ineboliviaoficial/
#    - title: dribbble
#      url: https://www.ine.gob.bo/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/IslpBolivia
  - title: facebook
    url: https://www.facebook.com/islpBolivia/

# Postal address (add as many lines as necessary)
address:
  - line: La Paz - Bolivia

# Build settings
markdown: kramdown
permalink: pretty